# This is an experimental environment
# Everything is contained in one image
version: '2'
services:
    docker-ssh-lamp:
        build:
          context: ..
          dockerfile: ./docker/Dockerfile
        hostname: docker-ssh-lamp
        image: docker-ssh-lamp
        volumes:
          - ./app:/app
          - ./mysql:/var/lib/mysql
          - ./var_log:/var/log
        ports:
          - "2080:80" # Both 2080 and 8000 port are using apache
          - "2022:22"
          - "2036:3306"
        container_name: "jf-docker-ubuntu-ssh-lamp"
        entrypoint: /app/docker_start.sh
